//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC.SkillsDatabase.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TC.SkillsDatabase.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySuccesfullyCreated.
        /// </summary>
        public static string CategorySuccesfullyCreated {
            get {
                return ResourceManager.GetString("CategorySuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySuccesfullyDeleted.
        /// </summary>
        public static string CategorySuccesfullyDeleted {
            get {
                return ResourceManager.GetString("CategorySuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategorySuccesfullyUpdated.
        /// </summary>
        public static string CategorySuccesfullyUpdated {
            get {
                return ResourceManager.GetString("CategorySuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DublicateCategoryName.
        /// </summary>
        public static string DublicateCategoryName {
            get {
                return ResourceManager.GetString("DublicateCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DublicateLocationName.
        /// </summary>
        public static string DublicateLocationName {
            get {
                return ResourceManager.GetString("DublicateLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DublicateResourceName.
        /// </summary>
        public static string DublicateResourceName {
            get {
                return ResourceManager.GetString("DublicateResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DublicateResourceRoleName.
        /// </summary>
        public static string DublicateResourceRoleName {
            get {
                return ResourceManager.GetString("DublicateResourceRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DublicateTeamName.
        /// </summary>
        public static string DublicateTeamName {
            get {
                return ResourceManager.GetString("DublicateTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DublicateUserEmail.
        /// </summary>
        public static string DublicateUserEmail {
            get {
                return ResourceManager.GetString("DublicateUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSkillLevelName.
        /// </summary>
        public static string DuplicateSkillLevelName {
            get {
                return ResourceManager.GetString("DuplicateSkillLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateSkillName.
        /// </summary>
        public static string DuplicateSkillName {
            get {
                return ResourceManager.GetString("DuplicateSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationSuccesfullyCreated.
        /// </summary>
        public static string LocationSuccesfullyCreated {
            get {
                return ResourceManager.GetString("LocationSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationSuccesfullyDeleted.
        /// </summary>
        public static string LocationSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("LocationSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationSuccesfullyUpdated.
        /// </summary>
        public static string LocationSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("LocationSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileSuccesfullyUpdated.
        /// </summary>
        public static string ProfileSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("ProfileSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceRoleSuccesfullyCreated.
        /// </summary>
        public static string ResourceRoleSuccesfullyCreated {
            get {
                return ResourceManager.GetString("ResourceRoleSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceRoleSuccesfullyDeleted.
        /// </summary>
        public static string ResourceRoleSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("ResourceRoleSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceRoleSuccesfullyUpdated.
        /// </summary>
        public static string ResourceRoleSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("ResourceRoleSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceSkillSuccesfullyCreated.
        /// </summary>
        public static string ResourceSkillSuccesfullyCreated {
            get {
                return ResourceManager.GetString("ResourceSkillSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceSkillSuccesfullyDeleted.
        /// </summary>
        public static string ResourceSkillSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("ResourceSkillSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceSkillSuccesfullyUpdated.
        /// </summary>
        public static string ResourceSkillSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("ResourceSkillSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceSuccesfullyCreated.
        /// </summary>
        public static string ResourceSuccesfullyCreated {
            get {
                return ResourceManager.GetString("ResourceSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceSuccesfullyDeleted.
        /// </summary>
        public static string ResourceSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("ResourceSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceSuccesfullyUpdated.
        /// </summary>
        public static string ResourceSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("ResourceSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkillLevelSuccesfullyCreated.
        /// </summary>
        public static string SkillLevelSuccesfullyCreated {
            get {
                return ResourceManager.GetString("SkillLevelSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkillLevelSuccesfullyDeleted.
        /// </summary>
        public static string SkillLevelSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("SkillLevelSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkillLevelSuccesfullyUpdated.
        /// </summary>
        public static string SkillLevelSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("SkillLevelSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkillSuccesfullyCreated.
        /// </summary>
        public static string SkillSuccesfullyCreated {
            get {
                return ResourceManager.GetString("SkillSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkillSuccesfullyDeleted.
        /// </summary>
        public static string SkillSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("SkillSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkillSuccesfullyUpdated.
        /// </summary>
        public static string SkillSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("SkillSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamSuccesfullyCreated.
        /// </summary>
        public static string TeamSuccesfullyCreated {
            get {
                return ResourceManager.GetString("TeamSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamSuccesfullyDeleted.
        /// </summary>
        public static string TeamSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("TeamSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamSuccesfullyUpdated.
        /// </summary>
        public static string TeamSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("TeamSuccesfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSuccesfullyCreated.
        /// </summary>
        public static string UserSuccesfullyCreated {
            get {
                return ResourceManager.GetString("UserSuccesfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSuccesfullyDeleted.
        /// </summary>
        public static string UserSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("UserSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSuccesfullyUpdated.
        /// </summary>
        public static string UserSuccesfullyUpdated {
            get {
                return ResourceManager.GetString("UserSuccesfullyUpdated", resourceCulture);
            }
        }
    }
}
